//
//  ADNStyleKit.swift
//  Jupp
//
//  Created by Dominik Hauser on 04.07.14.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

class ADNStyleKit : NSObject {

    //// Cache

    struct Cache {
        static var backgroundColor: UIColor = UIColor(red: 0.188, green: 0.196, blue: 0.267, alpha: 1.000)
        static var theTextColor: UIColor = UIColor(red: 0.795, green: 0.800, blue: 0.320, alpha: 1.000)
    }

    //// Initialization

    override class func load() {
    }

    //// Colors

    class var backgroundColor: UIColor { return Cache.backgroundColor }
    class var theTextColor: UIColor { return Cache.theTextColor }

    //// Drawing Methods

    class func drawLoginScreen() {

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRectMake(69, 4, 129, 113))
        ADNStyleKit.backgroundColor.setFill()
        rectanglePath.fill()


        //// Text Drawing
        let textRect: CGRect = CGRectMake(85, 29, 98, 30)
        let textStyle = NSMutableParagraphStyle.defaultParagraphStyle().mutableCopy() as NSMutableParagraphStyle
        textStyle.alignment = NSTextAlignment.Center;

        let textFontAttributes = [NSFontAttributeName: UIFont(name: "Helvetica", size: 12), NSForegroundColorAttributeName: ADNStyleKit.theTextColor, NSParagraphStyleAttributeName: textStyle]

        "Hello, World!".drawInRect(textRect, withAttributes: textFontAttributes);
    }

}

@objc protocol StyleKitSettableImage {
    var image: UIImage! { get set }
}

@objc protocol StyleKitSettableSelectedImage {
    var selectedImage: UIImage! { get set }
}
